### ISSUE TITLE
Custom colour drop down

### ISSUE THREAD

**Issue by ktjaco** [nrenner/leaflet-raw-dem#1]
I was wondering if it is possible to add a custom colour scheme to the DEM BIL file. I see that in the leaflet-raw-dem.js file you can add another colour to the list but when I try that it isn't displaying on the drop down menu.

**Comment by nrenner** [comment]
Yes, you should be able to extend the color drop-down by adding properties to the `L.colors` object/map (see [js/colors.js](https://github.com/nrenner/leaflet-raw-dem/blob/master/js/colors.js)). Where the key is the name for the drop-down and the value is an array of colors in one of the formats supported by chroma.js, see [chroma.scale](http://gka.github.io/chroma.js/#chroma-scale), or a [ColorBrewer key](http://gka.github.io/chroma.js/#chroma-brewer).

For example by adding this to `index.html`, right before loading [`js/index.js`](https://github.com/nrenner/leaflet-raw-dem/blob/master/index.html#L19):

```
  <script>
    L.colors['RGB'] = ['#ff0000','#00ff00', '#0000ff'];
  </script>
```

**Comment by nrenner** [comment]
Mapzen has just released gobal terrain tiles for Tangram as a preview, probably the way to go:
https://mapzen.com/blog/elevation/

**Comment by ktjaco** [comment]
@nrenner Thank you! I really like this plug-in and it is probably the best use for easily visualizing elevation.
